language: scala
sudo: false
jdk: openjdk8
scala:
  - 2.12.10

notifications:
  email:
    on_success: never
    on_failure: never

cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt
  - $HOME/.cache/coursier

before_cache:
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
- find $HOME/.sbt        -name "*.lock"               -print -delete

script:
- sbt clean coverage test coverageReport &&
  sbt coverageAggregate

after_success:
- sbt coveralls
